// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4_ox5o078RGtvHR_r3t9hwESAJpv21c',
    appId: '1:1077339885999:web:48f7f8d9a9dedae3845f5a',
    messagingSenderId: '1077339885999',
    projectId: 'intostudy-9b377',
    authDomain: 'intostudy-9b377.firebaseapp.com',
    storageBucket: 'intostudy-9b377.firebasestorage.app',
    measurementId: 'G-8LHJHSPQ6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6jvnRudSLzorNs9MzhYZXl7Ofz6qG-n0',
    appId: '1:1077339885999:android:2ae9e9511214ca89845f5a',
    messagingSenderId: '1077339885999',
    projectId: 'intostudy-9b377',
    storageBucket: 'intostudy-9b377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm6jFFaloSky8RwYpddh212TLb8SP5IXY',
    appId: '1:1077339885999:ios:1e3b31296e12bc39845f5a',
    messagingSenderId: '1077339885999',
    projectId: 'intostudy-9b377',
    storageBucket: 'intostudy-9b377.firebasestorage.app',
    iosBundleId: 'com.example.intoStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm6jFFaloSky8RwYpddh212TLb8SP5IXY',
    appId: '1:1077339885999:ios:1e3b31296e12bc39845f5a',
    messagingSenderId: '1077339885999',
    projectId: 'intostudy-9b377',
    storageBucket: 'intostudy-9b377.firebasestorage.app',
    iosBundleId: 'com.example.intoStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj4_ox5o078RGtvHR_r3t9hwESAJpv21c',
    appId: '1:1077339885999:web:d9acc88cbd72833e845f5a',
    messagingSenderId: '1077339885999',
    projectId: 'intostudy-9b377',
    authDomain: 'intostudy-9b377.firebaseapp.com',
    storageBucket: 'intostudy-9b377.firebasestorage.app',
    measurementId: 'G-KZG9229M0V',
  );
}
